# config/routes.yaml
api_login_check:
  path: /api/login_check

controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

paypal_payment:
  path: /api/paypal/payment
  controller: App\Controller\PayPalController::createPayment
  methods: POST
